version: "3.8"
services:
  kmttg:
    image: drnay/kmttg:latest
    volumes:
      - kmttg_app:/home/kmttg/app
      - kmttg_files:/files
      - kmttg_out:/home/kmttg/out
    environment:
      - DISPLAY=novnc:0.0
      - TZ=America/Los_Angeles
    ports:
      - "8181:8181"
    depends_on:
      - novnc
    networks:
      - x11
  novnc:
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
      - RUN_FLUXBOX=no
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:
volumes:
  kmttg_app:
  kmttg_files:
  kmttg_out:
